version: '2'
services:
  container-crontab:
    image: 10.255.18.31/container-crontab:v0.1.0
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      io.rancher.scheduler.global: true
      io.rancher.container.hostname_override: container_name
